### ISSUE TITLE
State is wrong. Did you make sure to actually hit the login url first?

### ISSUE THREAD

**Issue by hybrid1969** [fuzzysteve/eve-sso-auth#2]
I started getting this error randomly for no apparent reason and cant see any obvious reason for it.

Any ideas?

Im also trying to port this to laravel and get the same error? Any idea or suggestions?

**Comment by fuzzysteve** [comment]
hmm. It suggests that there's an issue with the session? When you log in, you have the it first set up the session, (including the state) then it needs to validate that it matches when it comes back.

It'll break on a 30 minute inactivity, for example.
